### ISSUE TITLE
TODO: missing functions

### ISSUE THREAD

**Issue by rubo77** [rubo77/php-mysql-fix#5]
- [ ] mysql_client_encoding
- [ ] mysql_create_db
- [ ] mysql_drop_db
- [x] mysql_fetch_field
- [ ] mysql_fetch_lengths
- [ ] mysql_field_flags
- [x] mysql_field_len
- [ ] mysql_field_seek
- [ ] mysql_field_table
- [x] mysql_field_type
- [ ] mysql_get_client_info
- [ ] mysql_get_host_info
- [ ] mysql_get_proto_info
- [ ] mysql_info
- [ ] mysql_list_dbs
- [ ] mysql_list_fields
- [ ] mysql_list_processes
- [x] mysql_num_fields
- [ ] mysql_tablename
- [ ] mysql_stat
- [ ] mysql_thread_id
- [ ] mysql_unbuffered_query
